# artemis broker configuration
# check always ports on docker
artemis.broker.url=amqp://localhost:61616
artemis.broker.username=artemis
artemis.broker.password=artemis


#camel context
camel.app.lifetime.milliseconds=950000

# attiva una route alla volta, separando i nomi delle route con una virgola
camel.app.routes.enabled=recipientlist