#camel context
camel.app.lifetime.milliseconds=950000



camel.property.noop=true

camel.files.input.path=src/main/resources/files
camel.files.output.path=src/main/resources/files/output


camel.beans.exchangeMapper.name=exchangeMapper
camel.beans.exchangeMapper.class=com.messages.bean.ExchangeMapper